### ISSUE TITLE
Debian 11 Nginx/MariaDB 10.5/Php7.4 - No database connection, check your database credentials in your configuration file.

### ISSUE THREAD

**Issue by erasedhammer99** [Leantime/docs#8]
Hopefully I can get some help regarding a more custom installation. I am on debian 11, so mysql isn't exactly supported. I am instead running MariaDB 10.5 (with nginx and php7.4) and I am having some trouble getting the web interface to work.

Going to the url https://server/install I get:
`No database connection, check your database credentials in your configuration file.`

I have verified that I can log in to mariadb with the user and password I put in the configuration.php.

Is this setup just too unsupported to work?

**Comment by marcelfolaron** [comment]
Do you see any issues in resources/logs/error.log ?
Can you verify that the account information in configuration.php is
correct?

**Comment by erasedhammer99** [comment]
I actually just solved it, I uninstalled mariadb 10.5 and added mysql 8 from Ubuntu repository and it now works correctly

**Comment by marcelfolaron** [comment]
Great, thanks for the update
